"""Two-field manufactured-solution accuracy test (Figure 1 of the paper).

Measures error at the final time in the model's own energy quantities, as defined in
Section 4.1:

  displacement  ||e_u||_E = ( int_Omega sigma_e(e_u) : grad(e_u) )^(1/2)
                the elastic energy norm, i.e. the quadratic form behind the discrete
                energy identity; equivalent to the H^1 seminorm. The plain H^1
                seminorm is also reported as a cross-check (same rate, different
                constant), and the L2 norm for reference.

  density       ( int_Omega D_omega )^(1/2), where D_omega is the Bregman divergence
                generated by the fluid free energy omega,
                    D_omega(a||b) = omega(a) - omega(b) - omega_rho(b) (a - b) >= 0.
                Computed with porousflow.omega / .domega directly, so it matches the
                free energy the solver actually assembles.

The manufactured solution keeps the displacement-density coupling genuinely active:
u* = eps sin(2 pi t) u0(x) has d/dt u* nonzero throughout (cos(2 pi t) ~ 1 at the short
times used), so the term alpha rho_f d/dt u is O(1) rather than vanishing. Both forcing
terms f1 and f3 are derived for this solution; the grad(rho*) . u0 part of f3 integrates
to zero over the domain but does not vanish pointwise and is required for exactness.

Runs two sweeps, both at the benchmark parameters (E=1, nu=0.2, kappa=1, M=alpha=1):
  spatial   K = 8, 16, 32   at dt = 1e-6, T = 5e-6  (dt << h^2/(kappa pi^2), so the
                                                     temporal error stays below spatial)
  temporal  dt = 0.01, 0.005, 0.0025 at K = 256, T = 0.1  (K chosen so the spatial
                                                           error stays well below the
                                                           temporal error)

Writes data/accuracy/spatial.csv and data/accuracy/temporal_K256.csv.
Runtime: the temporal sweep is the expensive part (~1 h; ~45 s/step at K=256).
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from porousflow import *

base_output = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "accuracy")
ensure_dir(base_output)

eps = 0.1
pi = np.pi
coeff = 8*pi**2*(5/12) + 4*pi**2*(5/18)


def build_and_run(K, dt, T, tag, kappa, omega):
    kM2 = kappa*1.0*2*pi**2  # M=1
    pde = PorousFlow(mu=5/12, lam=5/18, a=1.0, k=kappa, M=1.0, p=1)
    pde.set_parameters(dt=dt, K=K, T=T, formulation="twofield",
                       ptype="fieldsplit", FrequencyOutput=1, cell_type=CellType.triangle)
    pde.setup_spaces(build_boundary=False)
    u_trial, rho_trial, u_test, rho_test = pde.test_and_trial_functions()
    u=Function(pde.spaces.Uspace); rho=Function(pde.spaces.Pspace)
    u_prev=Function(pde.spaces.Uspace); rho_prev=Function(pde.spaces.Pspace)
    t_c=Constant(pde.spaces.mesh,PETSc.ScalarType(0.0))
    t_mid_c=Constant(pde.spaces.mesh,PETSc.ScalarType(0.0))
    x=ufl.SpatialCoordinate(pde.spaces.mesh)

    u0 = ufl.as_vector([ufl.sin(2*pi*x[0])*(1-ufl.cos(2*pi*x[1])),
                        ufl.sin(2*pi*x[1])*(1-ufl.cos(2*pi*x[0]))])
    div_sigma_u0 = coeff*ufl.as_vector([
        ufl.sin(2*pi*x[0])*(2*ufl.cos(2*pi*x[1])-1),
        ufl.sin(2*pi*x[1])*(2*ufl.cos(2*pi*x[0])-1),
    ])

    # exact solution (evaluated at physical time t_c, for error measurement)
    u_ex = eps*ufl.sin(omega*t_c)*u0
    rho_ex = 2 - ufl.exp(-kM2*t_c)*ufl.cos(pi*x[0])*ufl.cos(pi*x[1])

    # forcing terms, evaluated at t_mid_c (centered-forcing convention)
    rho_ex_mid = 2 - ufl.exp(-kM2*t_mid_c)*ufl.cos(pi*x[0])*ufl.cos(pi*x[1])
    grad_rho_ex_mid = ufl.grad(rho_ex_mid)
    sin_mid = ufl.sin(omega*t_mid_c); cos_mid = ufl.cos(omega*t_mid_c)

    grad_p_mid = pi*ufl.exp(-kM2*t_mid_c)*ufl.as_vector([
        ufl.sin(pi*x[0])*ufl.cos(pi*x[1]),
        ufl.cos(pi*x[0])*ufl.sin(pi*x[1]),
    ])
    f1 = -eps*sin_mid*div_sigma_u0 + 1.0*grad_p_mid  # alpha=1

    dudt_mid = eps*omega*cos_mid*u0  # d/dt(u*) at t_mid_c
    f3 = 1.0*(rho_ex_mid*ufl.div(dudt_mid) + ufl.dot(grad_rho_ex_mid, dudt_mid))  # alpha=1

    e_u = u - u_ex
    e_rho = rho - rho_ex

    # --- error forms ---
    L2_u_f  = form(ufl.inner(e_u, e_u)*dx)
    L2_r_f  = form(e_rho**2*dx)
    En_u_f  = form(ufl.inner(pde.sigma(e_u), grad(e_u))*dx)      # elastic energy norm^2
    H1_u_f  = form(ufl.inner(grad(e_u), grad(e_u))*dx)           # plain H1 seminorm^2 (cross-check)
    Breg_r_f = form((pde.omega(rho) - pde.omega(rho_ex)
                     - pde.domega(rho_ex)*e_rho)*dx)             # Bregman divergence (energy norm^2)

    noslip = np.zeros(pde.spaces.mesh.geometry.dim, dtype=PETSc.ScalarType)
    U_bc = dirichletbc(noslip, pde.spaces.Uspace_boundary_dofs, pde.spaces.Uspace); bcs=[U_bc]

    u.x.array[:] = 0.0  # u*(x,0) = eps*sin(0)*u0(x) = 0
    rho.interpolate(lambda xp: (2-np.cos(pi*xp[0])*np.cos(pi*xp[1]))/1.0)
    pde.assign_function(u_prev,u); pde.assign_function(rho_prev,rho)

    dt_c=Constant(pde.spaces.mesh,PETSc.ScalarType(dt))
    half=Constant(pde.spaces.mesh,PETSc.ScalarType(0.5))
    stab=Constant(pde.spaces.mesh,PETSc.ScalarType(dt))
    avg_rho=half*(rho+rho_prev)
    avg_domg=(avg_rho*grad(pde.domega(rho_prev))+rho_prev*grad(pde.d2omega(rho_prev)*(rho-rho_prev)))
    R_u=(half*inner(pde.sigma((1+stab)*u+(1-stab)*u_prev),grad(u_test))*dx
         +dot(avg_domg,pde.a*u_test)*dx-dot(f1,u_test)*dx)
    R_rho=(dot(avg_domg,dt_c*pde.k*grad(rho_test))*dx
           +dot(-pde.a*avg_rho*(u-u_prev),grad(rho_test))*dx
           +(rho-rho_prev)*rho_test*dx
           -dt_c*f3*rho_test*dx)
    J11=ufl.derivative(R_u,u,u_trial); J12=ufl.derivative(R_u,rho,rho_trial)
    J21=ufl.derivative(R_rho,u,u_trial); J22=ufl.derivative(R_rho,rho,rho_trial)
    problem=NonlinearProblem([R_u,R_rho],[u,rho],bcs=bcs,
        J=[[J11,J12],[J21,J22]],P=[[J11,None],[None,J22]],kind="nest",
        petsc_options_prefix=f"pf2cen{tag}_",
        petsc_options={"snes_type":"newtonls","snes_rtol":1e-9,"snes_atol":1e-12,
                       "snes_max_it":60,"ksp_type":"gmres","ksp_rtol":1e-8,
                       "ksp_atol":1e-12,"pc_type":"fieldsplit"})
    ksp=problem.solver.getKSP(); pc=ksp.getPC()
    pc.setType("fieldsplit"); pc.setFieldSplitType(PETSc.PC.CompositeType.ADDITIVE)
    row_is,_=problem.A.getNestISs(); pc.setFieldSplitIS(("u",row_is[0]),("rho",row_is[1]))
    pfx=ksp.getOptionsPrefix(); opts=PETSc.Options()
    opts[f"{pfx}fieldsplit_u_ksp_type"]="preonly"; opts[f"{pfx}fieldsplit_u_pc_type"]="hypre"
    opts[f"{pfx}fieldsplit_u_pc_hypre_type"]="boomeramg"
    opts[f"{pfx}fieldsplit_rho_ksp_type"]="preonly"; opts[f"{pfx}fieldsplit_rho_pc_type"]="jacobi"
    problem.solver.setFromOptions()

    comm=pde.spaces.mesh.comm; t=0.0
    L2_u_fin=L2_r_fin=En_u_fin=H1_u_fin=Breg_r_fin=np.nan
    num_steps=int(round(T/dt))
    for step in range(num_steps):
        t+=dt; t_c.value=PETSc.ScalarType(t)
        t_mid_c.value=PETSc.ScalarType(t-(1-dt)*dt/2)
        pde.assign_function(u_prev,u); pde.assign_function(rho_prev,rho)
        pde.assign_function(u,u_prev); pde.assign_function(rho,rho_prev)
        problem.solve()
        if problem.solver.getConvergedReason()<=0:
            if comm.rank==0: print(f"  [WARNING] {tag} step={step} failed to converge")
            break
        L2_u_fin=np.sqrt(comm.allreduce(assemble_scalar(L2_u_f),op=MPI.SUM))
        L2_r_fin=np.sqrt(comm.allreduce(assemble_scalar(L2_r_f),op=MPI.SUM))
        En_u_fin=np.sqrt(abs(comm.allreduce(assemble_scalar(En_u_f),op=MPI.SUM)))
        H1_u_fin=np.sqrt(abs(comm.allreduce(assemble_scalar(H1_u_f),op=MPI.SUM)))
        Breg_r_fin=np.sqrt(abs(comm.allreduce(assemble_scalar(Breg_r_f),op=MPI.SUM)))
    return L2_u_fin, L2_r_fin, En_u_fin, H1_u_fin, Breg_r_fin, comm


def rate(prev_val, val, prev_x, x):
    return np.log(prev_val/val)/np.log(prev_x/x)


# Benchmark closure parameters, shared by both sweeps (Section 4.1).
K_temp = 256; T_temp = 0.1
kappa_shared = 1.0
omega_shared = 2*pi

# ── Spatial convergence (K=[8,16,32], dt=1e-6, T=5e-6) ──
K_array = [8, 16, 32]
dt_spatial = 1e-6
T_spatial  = 5e-6

spatial_rows = []
for K in K_array:
    L2_u, L2_r, En_u, H1_u, Breg_r, comm = build_and_run(
        K, dt_spatial, T_spatial, f"sK{K}", kappa=kappa_shared, omega=omega_shared)
    if comm.rank==0:
        print(f"[2f-coupled spatial K={K}] L2_u={L2_u:.3e}  En_u={En_u:.3e}  H1_u={H1_u:.3e}  "
              f"L2_rho={L2_r:.3e}  Breg_rho={Breg_r:.3e}")
    spatial_rows.append({"K":K,"h":1/K,"dt":dt_spatial,
                          "L2_u":L2_u,"En_u":En_u,"H1_u":H1_u,
                          "L2_rho":L2_r,"Breg_rho":Breg_r})

if comm.rank==0:
    print("\n--- Spatial convergence (2-field COUPLED, dt=1e-6): L2 vs energy norms ---")
    for i,r in enumerate(spatial_rows):
        if i==0:
            print(f"  K={r['K']}  L2_u={r['L2_u']:.3e}  En_u={r['En_u']:.3e}  H1_u={r['H1_u']:.3e}"
                  f"  L2_rho={r['L2_rho']:.3e}  Breg_rho={r['Breg_rho']:.3e}  ---")
        else:
            p=spatial_rows[i-1]
            print(f"  K={r['K']}  "
                  f"L2_u={r['L2_u']:.3e}({rate(p['L2_u'],r['L2_u'],p['h'],r['h']):.2f})  "
                  f"En_u={r['En_u']:.3e}({rate(p['En_u'],r['En_u'],p['h'],r['h']):.2f})  "
                  f"H1_u={r['H1_u']:.3e}({rate(p['H1_u'],r['H1_u'],p['h'],r['h']):.2f})  "
                  f"L2_rho={r['L2_rho']:.3e}({rate(p['L2_rho'],r['L2_rho'],p['h'],r['h']):.2f})  "
                  f"Breg_rho={r['Breg_rho']:.3e}({rate(p['Breg_rho'],r['Breg_rho'],p['h'],r['h']):.2f})")
write_csv(os.path.join(base_output,"spatial.csv"),
          ["K","h","dt","L2_u","En_u","H1_u","L2_rho","Breg_rho"],spatial_rows)

# ── Temporal convergence (K=196, dt=[0.05,0.025,0.0125,0.00625], T=0.5) ──
dt_array_t = [0.01, 0.005, 0.0025]

temporal_rows = []
for dt in dt_array_t:
    L2_u, L2_r, En_u, H1_u, Breg_r, comm = build_and_run(
        K_temp, dt, T_temp, f"t{int(dt*1e4)}", kappa=kappa_shared, omega=omega_shared)
    if comm.rank==0:
        print(f"[2f-coupled temporal dt={dt}] L2_u={L2_u:.3e}  En_u={En_u:.3e}  H1_u={H1_u:.3e}  "
              f"L2_rho={L2_r:.3e}  Breg_rho={Breg_r:.3e}")
    temporal_rows.append({"dt":dt,"L2_u":L2_u,"En_u":En_u,"H1_u":H1_u,
                           "L2_rho":L2_r,"Breg_rho":Breg_r})

if comm.rank==0:
    print(f"\n--- Temporal convergence (2-field, T={T_temp}): L2 vs energy norms ---")
    for i,r in enumerate(temporal_rows):
        if i==0:
            print(f"  dt={r['dt']:.4f}  L2_u={r['L2_u']:.3e}  En_u={r['En_u']:.3e}  H1_u={r['H1_u']:.3e}"
                  f"  L2_rho={r['L2_rho']:.3e}  Breg_rho={r['Breg_rho']:.3e}  ---")
        else:
            p=temporal_rows[i-1]
            print(f"  dt={r['dt']:.4f}  "
                  f"L2_u={r['L2_u']:.3e}({rate(p['L2_u'],r['L2_u'],p['dt'],r['dt']):.2f})  "
                  f"En_u={r['En_u']:.3e}({rate(p['En_u'],r['En_u'],p['dt'],r['dt']):.2f})  "
                  f"H1_u={r['H1_u']:.3e}({rate(p['H1_u'],r['H1_u'],p['dt'],r['dt']):.2f})  "
                  f"L2_rho={r['L2_rho']:.3e}({rate(p['L2_rho'],r['L2_rho'],p['dt'],r['dt']):.2f})  "
                  f"Breg_rho={r['Breg_rho']:.3e}({rate(p['Breg_rho'],r['Breg_rho'],p['dt'],r['dt']):.2f})")
write_csv(os.path.join(base_output,f"temporal_K{K_temp}.csv"),
          ["dt","L2_u","En_u","H1_u","L2_rho","Breg_rho"],temporal_rows)
print(f"Done. {base_output}")
